# Generated by Django 2.1 on 2018-08-15 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180815_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='disorder',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disorder',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
