# Generated by Django 2.1 on 2018-08-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180815_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='disorder',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
