# Generated by Django 2.1 on 2018-08-15 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180815_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='disorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Disorder'),
        ),
    ]
