# Generated by Django 2.1 on 2018-08-15 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180815_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='disorder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Disorder'),
            preserve_default=False,
        ),
    ]
