# Generated by Django 2.1 on 2018-08-20 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_blogpost_disorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('img_url', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('disorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Disorder')),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
