# Generated by Django 2.1 on 2018-08-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180820_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localresource',
            name='img_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='localresource',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
