# Generated by Django 2.1 on 2018-08-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180820_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.CharField(max_length=5000, unique=True),
        ),
    ]
